using System;using System.IO;using System.Reflection;using System.Runtime.InteropServices;using System.Security.Cryptography;using System.Linq;using TxTools.ExportByColor;
class RoundHoleDirectRegression
{
 static string bin;
 [STAThread]static int Main(string[] args){bin=args[2];AppDomain.CurrentDomain.AssemblyResolve+=(s,e)=>{var p=Path.Combine(bin,new AssemblyName(e.Name).Name+".dll");return File.Exists(p)?Assembly.LoadFrom(p):null;};try{Run(args);return 0;}catch(Exception e){Console.Error.WriteLine(e);return 1;}}
 static string Hash(string p){using(var h=SHA256.Create())using(var s=File.OpenRead(p))return BitConverter.ToString(h.ComputeHash(s));}
 static void Run(string[] args){string dir=Path.GetFullPath(args[1]);Directory.CreateDirectory(dir);string cgr=Path.Combine(dir,"fixture.cgr");var holes=JtDirectBridge.ConvertToCgrWithHoles(args[0],dir,Path.Combine(bin,"JtDirectCs","TxTools.JtDecoder.exe"),cgr,new double[]{1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1},CgrBackend.LineFace,Console.WriteLine);
  if(holes.Count==0||File.ReadAllLines(cgr+".holes.csv").Length!=holes.Count+1)throw new Exception("Hole sidecar mismatch");if(args.Length>3&&Hash(cgr)!=Hash(args[3]))throw new Exception("Hole analysis changed CGR geometry bytes");
  var app=(INFITF.Application)Marshal.GetActiveObject("CATIA.Application");string part=Path.Combine(dir,"hole_references.CATPart");var report=RoundHoleCatiaWriter.WritePart(app,holes,part,false,message=>{if(message.Contains("axis ready")&& !message.Contains("hole=1 ")&&!message.Contains("hole=100 ")&&!message.Contains("hole=200 ")&&!message.Contains("hole=300 ")&&!message.Contains("hole=400 ")&&!message.Contains("hole=500 ")&&!message.Contains("hole=600 ")&&!message.Contains("hole=700 ")&&!message.Contains("hole=800 "))return;if(message.Contains("update circle"))return;Console.WriteLine(message);});int expected=holes.Sum(h=>h.PairedRims?2:1);if(report.Circles!=expected||report.Cylinders!=0)throw new Exception("Analytic reference count mismatch");
  var doc=(ProductStructureTypeLib.ProductDocument)app.Documents.Add("Product");try{doc.Product.set_PartNumber("JT_CGR_ROUND_HOLE_TEST");var resource=doc.Product.Products.AddNewProduct("Fixture_With_Hole_References");resource.Products.AddComponentsFromFiles(new object[]{cgr,part},"All");if(doc.Product.Products.Count!=1||resource.Products.Count!=2)throw new Exception("Assembly insertion mismatch");doc.SaveAs(Path.Combine(dir,"validation.CATProduct"));var viewer=(INFITF.Viewer3D)app.ActiveWindow.ActiveViewer;viewer.RenderingMode=INFITF.CatRenderingMode.catRenderShading;viewer.Reframe();viewer.Update();viewer.CaptureToFile(INFITF.CatCaptureFormat.catCaptureFormatBMP,Path.Combine(dir,"validation.bmp"));}finally{doc.Close();}
  Console.WriteLine("PASS direct JT->CGR + native analytic hole reference CATPart->CATIA; candidates="+holes.Count+" circles="+report.Circles+" unchanged CGR bytes; SPA radius/axis measurements passed");
 }
}
