using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.Reflection;using TxTools.ExportByColor;
class RoundHoleCgrMeshRegression {
 static void Bore(List<float[]> v,List<CgrWriter.Face> f,int shape,bool ellipse=false){int n=32,start=v.Count;for(int ring=0;ring<4;ring++)for(int i=0;i<n;i++){double a=2*Math.PI*i/n,s=ring<2?1:2;v.Add(new[]{(float)(10*s*Math.Cos(a)),(float)((ellipse?12:10)*s*Math.Sin(a)),(float)(ring%2*20)});}Action<int,int,int> add=(a,b,c)=>f.Add(new CgrWriter.Face{Idx=new[]{start+a,start+c,start+b},Surface=shape,R=10,G=20,B=30,Opacity=127});for(int i=0;i<n;i++){int j=(i+1)%n;add(i,j,n+i);add(j,n+j,n+i);add(i,2*n+i,j);add(j,2*n+i,2*n+j);add(n+i,n+j,3*n+i);add(n+j,3*n+j,3*n+i);}}
 static void Assert(bool v,string message){if(!v)throw new Exception(message);}
 static int Main(string[] args){AppDomain.CurrentDomain.AssemblyResolve+=(s,e)=>{string path=Path.Combine(args[0],new AssemblyName(e.Name).Name+".dll");return System.IO.File.Exists(path)?Assembly.LoadFrom(path):null;};try{Run();return 0;}catch(Exception e){Console.Error.WriteLine(e);return 1;}}
 static void Run(){foreach(bool rotate in new[]{false,true}){var v=new List<float[]>();var f=new List<CgrWriter.Face>();Bore(v,f,1);Bore(v,f,2,true);if(rotate)for(int i=0;i<v.Count;i++){double x=v[i][0],y=v[i][1],z=v[i][2];v[i]=new[]{(float)(1000+x),(float)(2000-z),(float)(3000+y)};}
 var oldV=v.Select(p=>(float[])p.Clone()).ToList();var oldF=f.Select(p=>(int[])p.Idx.Clone()).ToList();var holes=RoundHoleReconstruction.Find(v,f);var rebuilt=RoundHoleCgrMesh.Replace(v,f,holes,Console.WriteLine);Assert(rebuilt.Cylinders.Count==1,"Supported bore was not replaced");Assert(rebuilt.RemovedWallTriangles==64,"Wrong original wall removal");Assert(rebuilt.Cylinders.Values.Single().SourceSurface==1,"Ellipse/coincident separate shape was replaced");Assert(rebuilt.Faces.All(face=>face.Opacity==127&&face.R==10&&face.G==20&&face.B==30),"RGBA changed");Assert(v.Select((p,i)=>p.SequenceEqual(oldV[i])).All(x=>x)&&f.Select((p,i)=>p.Idx.SequenceEqual(oldF[i])).All(x=>x),"Original mesh mutated");
 Assert(f.Select((face,index)=>new{face,index}).Where(x=>x.face.Surface==2).All(x=>!rebuilt.ChangedSourceTriangles.Contains(x.index)),"Unsupported shape touched");
 var cylinder=rebuilt.Cylinders.Values.Single();foreach(var face in rebuilt.Faces.Where(face=>face.Surface==cylinder.Surface))foreach(int i in face.Idx){var p=rebuilt.Vertices[i];double x=p[0]-cylinder.Center[0],y=p[1]-cylinder.Center[1],z=p[2]-cylinder.Center[2],axial=x*cylinder.Axis[0]+y*cylinder.Axis[1]+z*cylinder.Axis[2];double r=Math.Sqrt(Math.Max(0,x*x+y*y+z*z-axial*axial));Assert(Math.Abs(r-cylinder.Radius)<.001,"Replacement vertex off cylinder");}
 Console.WriteLine("PASS "+(rotate?"rotated/transformed":"axis Z")+" bore wall removal, cap replacement, RGBA, source immutability and shape isolation");}
 }
}
