using System;using System.IO;using System.Collections.Generic;using System.Linq;using System.Reflection;using TxTools.ExportByColor;
class RoundHoleRegression
{
 static void Mesh(int n,double rx,double ry,bool inward,double z,List<float[]> vs,List<CgrWriter.Face> fs,int surface=1)
 {
  int start=vs.Count;for(int ring=0;ring<4;ring++)for(int i=0;i<n;i++){double t=i*2*Math.PI/n;double scale=ring>=2?2:1;vs.Add(new[]{(float)(rx*Math.Cos(t)*scale),(float)(ry*Math.Sin(t)*scale),(float)(z+(ring%2)*20)});}
  Action<int,int,int> add=(a,b,c)=>fs.Add(new CgrWriter.Face{Idx=inward?new[]{start+a,start+c,start+b}:new[]{start+a,start+b,start+c},Surface=surface});
  for(int i=0;i<n;i++){int j=(i+1)%n;add(i,j,n+i);add(j,n+j,n+i);add(i,2*n+i,j);add(j,2*n+i,2*n+j);add(n+i,n+j,3*n+i);add(n+j,3*n+j,3*n+i);}
 }
 static void Assert(bool value,string message){if(!value)throw new Exception(message);}
 static int Main(string[] args){string root=args.Length==4?args[3]:args.Length==1?args[0]:@"E:\ProcessSimulatePlugin\Process Simulate\bin";AppDomain.CurrentDomain.AssemblyResolve+=(s,e)=>{var p=Path.Combine(root,new AssemblyName(e.Name).Name+".dll");return File.Exists(p)?Assembly.LoadFrom(p):null;};try{if(args.Length==3||args.Length==4){Analyze(args);return 0;}Tests();return 0;}catch(Exception e){Console.Error.WriteLine(e);return 1;}}
 static void Tests(){var vs=new List<float[]>();var fs=new List<CgrWriter.Face>();Mesh(32,10,10,true,0,vs,fs);var h=RoundHoleReconstruction.Find(vs,fs);Assert(h.Count==1&&h[0].PairedRims&&Math.Abs(h[0].Radius-10)<1e-5&&Math.Abs(h[0].Depth-20)<1e-5&&h[0].WallTriangleCount==64,"Known circular bore failed");
  for(int i=0;i<vs.Count;i++){double x=vs[i][0],y=vs[i][1],z=vs[i][2];vs[i]=new[]{(float)(100000+x),(float)(-3000-z),(float)(800+y)};}var original=vs.Select(v=>(float[])v.Clone()).ToArray();var indices=fs.Select(f=>(int[])f.Idx.Clone()).ToArray();h=RoundHoleReconstruction.Find(vs,fs);Assert(h.Count==1&&h[0].PairedRims&&Math.Abs(h[0].Radius-10)<0.01&&Math.Abs(h[0].Axis[1]-1)<1e-6,"Rotated translated bore failed");Assert(vs.Select((v,i)=>v.SequenceEqual(original[i])).All(x=>x)&&fs.Select((f,i)=>f.Idx.SequenceEqual(indices[i])).All(x=>x),"Analysis changed mesh");
  foreach(var test in new[]{"boss","ellipse","hexagon","open","cone","separate"}){vs=new List<float[]>();fs=new List<CgrWriter.Face>();Mesh(test=="hexagon"?6:32,10,test=="ellipse"?12:10,test!="boss",0,vs,fs);if(test=="open")fs.RemoveRange(0,6);if(test=="cone")for(int i=32;i<64;i++){vs[i][0]*=1.1f;vs[i][1]*=1.1f;}
   if(test=="separate"){Mesh(32,10,10,true,100,vs,fs);h=RoundHoleReconstruction.Find(vs,fs);Assert(h.Count==2&&h.All(x=>Math.Abs(x.Depth-20)<0.01),"Separate bores paired across empty space");}else{h=RoundHoleReconstruction.Find(vs,fs);Assert(h.Count==0,"False circular hole: "+test);}Console.WriteLine("PASS "+test);}
  vs=new List<float[]>();fs=new List<CgrWriter.Face>();Mesh(32,10,10,true,0,vs,fs);fs=fs.Where((f,i)=>i%6<4).ToList();h=RoundHoleReconstruction.Find(vs,fs);Assert(h.Count==1&&!h[0].PairedRims&&h[0].RimB==null&&h[0].Depth==0,"Single rim incorrectly assigned depth");Console.WriteLine("PASS single rim has no depth evidence");
  foreach(var test in new[]{"overlap","nonplanar","star","shape-isolation"}){vs=new List<float[]>();fs=new List<CgrWriter.Face>();int n=test=="star"?31:32;Mesh(n,10,10,true,0,vs,fs);if(test=="overlap"||test=="shape-isolation")Mesh(n,10,10,true,0,vs,fs,test=="overlap"?1:2);if(test=="nonplanar")foreach(var p in vs)p[2]+=p[0]*p[1]*0.1f;if(test=="star")for(int ring=0;ring<4;ring++)for(int i=0;i<n;i++){double t=i*4*Math.PI/n,r=ring>=2?20:10;vs[ring*n+i][0]=(float)(r*Math.Cos(t));vs[ring*n+i][1]=(float)(r*Math.Sin(t));}h=RoundHoleReconstruction.Find(vs,fs);Assert(h.Count==(test=="shape-isolation"?2:0),"Topology/circle guard failed: "+test);Console.WriteLine("PASS "+test);}
  Console.WriteLine("PASS exact/rotated/translated bore radius and depth; analysis leaves input mesh unchanged");
 }
 static void Analyze(string[] args){string source=args[0],meshPath=args[1];var mesh=JtDirectBridge.Read(meshPath,source);var fs=mesh.Faces.Select(f=>new CgrWriter.Face{Idx=f.Indices,R=f.R,G=f.G,B=f.B,Opacity=f.Alpha,Surface=f.Surface}).ToList();var timer=System.Diagnostics.Stopwatch.StartNew();var holes=RoundHoleReconstruction.Find(mesh.Vertices,fs);RoundHoleReconstruction.WriteCsv(args[2],holes);Console.WriteLine("HOLES="+holes.Count+" PAIRED="+holes.Count(h=>h.PairedRims)+" elapsed_ms="+timer.ElapsedMilliseconds);foreach(var h in holes.Take(15))Console.WriteLine("shape="+h.Surface+" radius="+h.Radius+" depth="+h.Depth+" error="+h.MaximumError+" triangles="+h.WallTriangleCount);}
}
